### ISSUE TITLE
No3 ビットすごろく

### ISSUE THREAD

**Issue by ShotaroSuzu** [ShotaroSuzu/yukicoder#4]
@maruyuki95  
コードレビューお願い！  
https://github.com/ShotaroSuzu/yukicoder/blob/master/src/yukicoder/level2/bitsugoroku/BitSugorokuRecursive.java

**Comment by maruyuki95** [comment]
https://github.com/ShotaroSuzu/yukicoder/blob/364cde1bbea5b13db3bfbd19f83a449d2df2869b/src/yukicoder/level2/bitsugoroku/BitSugorokuRecursive.java#L16
goalは、クラスの変数じゃなく、メソッドの変数にして、`calcMinimanMovingNumber`メソッドの引数にしたほうが良さそう。（メソッド内でgoalの変数が利用されるから）  
`read`と `output`をメソッドに切り出してるの丁寧で良いなと思った。 

https://github.com/ShotaroSuzu/yukicoder/blob/364cde1bbea5b13db3bfbd19f83a449d2df2869b/src/yukicoder/level2/bitsugoroku/BitSugorokuRecursive.java#L24
「minimum」？

https://github.com/ShotaroSuzu/yukicoder/blob/364cde1bbea5b13db3bfbd19f83a449d2df2869b/src/yukicoder/level2/bitsugoroku/BitSugorokuRecursive.java#L25
ここ`presentLocations`と`pastLocations`の変数を分けて渡してるの良いな、と思った。（私は同じ引数で渡してしまってた。。）
あと、コメントしてくれてたように`search`のメソッド名より、 `calcMinimanMovingNumber`のメソッド名のほうがわかりやすくていいね。

https://github.com/ShotaroSuzu/yukicoder/blob/364cde1bbea5b13db3bfbd19f83a449d2df2869b/src/yukicoder/level2/bitsugoroku/BitSugorokuRecursive.java#L34
メソッドのロジックが整理されてて読みやすいな、と思った。  

https://github.com/ShotaroSuzu/yukicoder/blob/364cde1bbea5b13db3bfbd19f83a449d2df2869b/src/yukicoder/level2/bitsugoroku/BitSugorokuRecursive.java#L62
「移動できるかどうか」の判定なので、確かに「can～」のメソッド名が適切だね

https://github.com/ShotaroSuzu/yukicoder/blob/364cde1bbea5b13db3bfbd19f83a449d2df2869b/src/yukicoder/level2/bitsugoroku/BitSugorokuRecursive.java#L77
ここもメソッド名わかりやすくていいな～
